name: 'Sonatype Stats'
description: 'Generates index.html and JSONs with stats downloaded from Sonatype Central Statistics'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  sonatype-project:
    description: 'Name of the project on Sonatype OSS'
    required: true
  sonatype-username:
    description: 'Username you use to login into Sonatype OSS'
    required: true
  sonatype-password:
    description: 'Password you use to login into Sonatype OSS'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Scala CLI
      uses: VirtusLab/scala-cli-setup@v1.1.3

    - name: Run Statistics generator
      run: scala-cli run "$GITHUB_ACTION_PATH"
      shell: bash
      env:
        SONATYPE_PROJECT: ${{ inputs.sonatype-project }}
        SONATYPE_USERNAME: ${{ inputs.sonatype-username }}
        SONATYPE_PASSWORD: ${{ inputs.sonatype-password }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
